[package]
name = "phoenix_uefi_alloc"
version = "0.1.2"
edition = "2021"
description = "UEFI allocation support"


[lib]
name = "uefi_alloc"

[dependencies]
phoenix-uefi = {git = "https://github.com/JakubGawron1/UEFI"}
